// User Roles
const USER_ROLES = {
  ADMIN: 'ADMIN',
  BAR_MANAGER: 'BAR_MANAGER',
  BAR_AGENT: 'BAR_AGENT',
  CONSUMER: 'CONSUMER'
};

// Question Types
const QUESTION_TYPES = {
  TEXT: 'TEXT',
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
  RATING: 'RATING',
  DATE: 'DATE',
  CHECKBOX: 'CHECKBOX'
};

// Questionnaire Status
const QUESTIONNAIRE_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED',
  CLOSED: 'CLOSED'
};

// Consent Types
const CONSENT_TYPES = {
  DATA_COLLECTION: 'DATA_COLLECTION',
  MARKETING: 'MARKETING',
  PROFILING: 'PROFILING',
  THIRD_PARTY: 'THIRD_PARTY'
};

// Error Codes
const ERROR_CODES = {
  // Authentication errors (1000-1099)
  INVALID_CREDENTIALS: 1001,
  TOKEN_EXPIRED: 1002,
  TOKEN_INVALID: 1003,
  USER_NOT_FOUND: 1004,

  // Authorization errors (1100-1199)
  UNAUTHORIZED: 1101,
  FORBIDDEN: 1102,
  INSUFFICIENT_PERMISSIONS: 1103,

  // Validation errors (2000-2099)
  VALIDATION_ERROR: 2001,
  INVALID_EMAIL: 2002,
  INVALID_PASSWORD: 2003,
  EMAIL_ALREADY_EXISTS: 2004,

  // Database errors (3000-3099)
  DATABASE_ERROR: 3001,
  RECORD_NOT_FOUND: 3002,
  DUPLICATE_ENTRY: 3003,

  // Business logic errors (4000-4099)
  BUSINESS_LOGIC_ERROR: 4001,
  INVALID_STATE: 4002,

  // Server errors (5000-5099)
  INTERNAL_SERVER_ERROR: 5001
};

module.exports = {
  USER_ROLES,
  QUESTION_TYPES,
  QUESTIONNAIRE_STATUS,
  CONSENT_TYPES,
  ERROR_CODES
};
